"""my change

Revision ID: 10f5df2bb575
Revises: 20250508_trade_logs
Create Date: 2025-05-09 03:08:04.398862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10f5df2bb575'
down_revision = '20250508_trade_logs'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
