"""describe change

Revision ID: 4d0d4eb33c70
Revises: 10f5df2bb575
Create Date: 2025-05-09 03:25:15.947494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d0d4eb33c70'
down_revision = '10f5df2bb575'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scoring_weights')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_weights',
    sa.Column('feature', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('feature', name='scoring_weights_pkey')
    )
    # ### end Alembic commands ###
