"""add context_json to trades

Revision ID: 5def40f0ac62
Revises: 4d0d4eb33c70
Create Date: 2025-05-09 04:09:45.838053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5def40f0ac62'
down_revision = '4d0d4eb33c70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('context_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'context_json')
    # ### end Alembic commands ###
